### ISSUE TITLE
Warning  message

### ISSUE THREAD

**Issue by erchengzhao** [agnesblch/MetIDfyR#1]
When analyze data from Waters Q-TOF, there is a warning message as follows：

Warning message:

In .extractMultipleChromatograms(object, rt = rt, mz = mz, aggregationFun = aggregationFun,  :

  No MS 1 data present.

There are no results in results folder.

**Comment by videlc** [comment]
From the Waters QTOF example files you provided via email, I was able to run MetIDfyR using the following workflow : 
After a quick look into the data, I was able to find a relevant m/z "271.1700"

1. conversion using msconvert to mzML with default parameters (no options, no peak-picking)

2. compound table named `waters_test_qtof.tsv` as follows :
```
name	formula	adduct_plus	adduct_minus	ms_file	ms2_reference_tsv
test	C18 H24 O2	H	H	input/ExampleAnalyte.mzML	
test	C18 H24 O2	H	H	input/ExampleControl.mzML	
test	C18 H24 O2	H	H	input/metabolite.mzML	
```

3. edit a config file `waters_qtof_config.R` with following parameters:
```
list_transfo = "input/list_transfo.tsv"
bool_phase_2 = TRUE
lib_perso = ""  # give the personnal R library if needed
nb_transformation = 1
cores = 2  # if NA cores = number of available cores -1
min_peak_intensity = 200
mz_ppm = 5  # confidence m/z to search chromatogram
rt_windows = 5  # windows size to consider a peak in chromatogram
nb_scan = 2  # minimum number of scans in chromatogram peaks
wdw_mz_ms2 = 45  # total window width
minimum_mz = 200 # Minimum M/Z value of a metabolite to be detected

```

4. run MetIDfyR with following command:
`system("Rscript MetIDfyR.R -i input/waters_test_qtof.tsv -o test_waters_results -c input/waters_qtof_config.R")`


5. R console log : 
```
> system("Rscript MetIDfyR.R -i input/waters_test_qtof.tsv -o test_waters_results -c input/waters_qtof_config.R")
### Initialisation ###
### CONFIGURATION ###
list_transfo = "input/list_transfo.tsv"
bool_phase_2 = TRUE
lib_perso = ""  # give the personnal R library if needed
nb_transformation = 1
cores = 2  # if NA cores = number of available cores -1
min_peak_intensity = 200
mz_ppm = 5  # confidence m/z to search chromatogram
rt_windows = 5  # windows size to consider a peak in chromatogram
nb_scan = 2  # minimum number of scans in chromatogram peaks
wdw_mz_ms2 = 45  # total window width
minimum_mz = 200 # Minimum M/Z value of a metabolite to be detected

### Select combination for test ###
### Do transformation for test ###
### Start chromatogram for test ###
### Create Directories ###
### Get reference MS2 ###
### Start foreach loop : 15 metabolites ###
### Execution time : test 0.98 mins ###
### Select combination for test ###
### Do transformation for test ###
### Start chromatogram for test ###
### Create Directories ###
### Get reference MS2 ###
### Start foreach loop : 15 metabolites ###
### Execution time : test 0.74 mins ###
### Select combination for test ###
### Do transformation for test ###
### Start chromatogram for test ###
### Create Directories ###
### Get reference MS2 ###
### Start foreach loop : 15 metabolites ###
Info: Can't find the parent retention time (number of peaks > 1) in minus
### Execution time : test 0.7 mins ###
Warning messages:
1: In .extractMultipleChromatograms(object, rt = rt, mz = mz, aggregationFun = aggregationFun,  :
  No MS 1 data present.
2: In .extractMultipleChromatograms(object, rt = rt, mz = mz, aggregationFun = aggregationFun,  :
  No MS 1 data present.
3: In .extractMultipleChromatograms(object, rt = rt, mz = mz, aggregationFun = aggregationFun,  :
  No MS 1 data present.
[1] 0
```

As you can see, I get the same warning message but there are results in the out_ folder -->

6. run `ui.R `(shiny app) and select output directory `out_test_metabolite_.....`

![image](https://user-images.githubusercontent.com/23085823/95173185-a2b3c780-07b8-11eb-8fd8-b9243577f128.png)

Metabolites are detected but no scoring is possible because no MS2 data is present.

example extracted ion chromatogram from the app : 
![image](https://user-images.githubusercontent.com/23085823/95173308-c840d100-07b8-11eb-933b-e2d678eba7a0.png)


We are investingating the warning message but the data can be analyzed to yield relevant identification.
We will implement MS1 scoring when only MS1 data is available.

**Comment by agnesbrnb** [comment]
inactive
